version: 2.1
orbs:
  jq: circleci/jq@1.9.1
  utils: coda/utils@0.5.0
  base-tools:
    commands:
      install:
        steps:
          - run:
              name: Install basic tools
              command: apt-get update && apt-get install -y pipenv

executors:
  default_build_environment:
    docker:
      - image: cimg/node:14.17
        auth:
          username: codainternaltools
          password: $DOCKERHUB_PASSWORD

commands:
  bootstrap_pipenv:
    steps:
      - restore_cache:
          name: Restore Cache - pipenv
          keys:
            - pipenv-{{ checksum "Pipfile.lock" }}
      - run:
          name: Bootstrap
          command: "make _bootstrap-python | while IFS= read -r line; do printf '[%s] %s\n' \"$(date '+%Y-%m-%d %H:%M:%S')\" \"$line\"; done"
      - save_cache:
          name: Save Cache - pipenv
          key: pipenv-{{ checksum "Pipfile.lock" }}
          paths:
            - /root/project/.venv # python
  bootstrap_node:
    steps:
      - restore_cache:
          name: Restore Cache - yarn
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: 'Install deps (node)'
          command: make _bootstrap-node
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

jobs:
  build:
    executor: default_build_environment
    working_directory: ~/repo

    steps:
      - checkout
      - base-tools/install
      - bootstrap_node
      - bootstrap_pipenv
      - run:
          name: 'Lint'
          command: make lint
      - run:
          name: 'Test'
          command: make test
      - run:
          name: 'Ensure clean dist diff'
          command: make validate-no-changes
  
  adhoc:
    executor: default_build_environment
    working_directory: ~/repo

    steps:
      - checkout
      # - restore_cache:
      #     name: Restore Cache - yarn
      #     keys:
      #       - v2-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v2-dependencies-
      - run:
          name: Bootstrap
          command: 'make bs'
      - run:
          name: Deploy Adhoc
          command: 'make publish-docs-adhoc'
      # TODO: add a probe step here to validate?

  head:
    executor: default_build_environment
    working_directory: ~/repo

    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v2-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v2-dependencies-
      - run:
          name: Bootstrap
          command: 'make bs'
      - run:
          name: Deploy Head
          command: 'make publish-docs-head'
      # TODO: add a probe step here to validate?
  
  staging:
    executor: default_build_environment
    working_directory: ~/repo

    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v2-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v2-dependencies-
      - run:
          name: Bootstrap
          command: 'make bs'
      - run:
          name: Deploy Staging
          command: 'make publish-docs-staging'
      # TODO: add a probe step here to validate?
  
  prod:
    executor: default_build_environment
    working_directory: ~/repo

    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v2-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v2-dependencies-
      - run:
          name: Bootstrap
          command: 'make bs'
      - run:
          name: Deploy Prod
          command: 'make publish-docs-prod'
      # TODO: add a probe step here to validate?

workflows:
  version: 2
  commit_validation:
    jobs:
      - build:
          context:
            - dockerhub

  deploy:
    jobs:
      - build:
          context:
            - dockerhub
          filters:
            branches:
              only:
                - sc-ci-deploy-docs
      - utils/cancel-older-awaiting-approvals:
          context:
            - dockerhub
            - util
          circle_token: ${CIRCLECI_TOKEN}
          requires:
            - build
      - head:
          context:
            - dockerhub
          requires:
            - build
      - staging:
          context:
            - dockerhub
          requires:
            - head
      - utils/slack-notify-waiting-for-approval:
          slack_bot_token: ${PUSH_REMINDER_BOT_TOKEN}
          requires:
            - staging
          context:
            - util
      - wait-for-approval:
          context:
            - dockerhub
          type: approval
          requires:
            - staging
      - prod:
          context:
            - dockerhub
          requires:
            - wait-for-approval
