name: Dependabot Pull Request Approve and Merge

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Checking the actor will prevent your Action run failing on non-Dependabot
    # PRs but also ensures that it only does work for Dependabot PRs.
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      # This first step will fail if there's no metadata and so the approval
      # will not occur.
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      # Here the PR gets approved.
      - name: Approve a PR
        # NOTE(spencer): this only works when the dependabot PR has only one dependency, which seems to always be the case right now
        # because `dependency_names` is a comma-separated string of all the dependencies, and `contains` syntax only works with one array.
        if: ${{ contains(fromJson(env.ALLOWED_DEPENDENCIES), steps.dependabot-metadata.outputs.dependency-names }}
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NOTE(spencer): ideally, we could support regex matching here like @types/*, but that's not supported by the Github Actions syntax.
          # We would need to do a custom bash script to "exit" based on a match.
          ALLOWED_DEPENDENCIES: '["@types/xml2js"]'
      # Finally, this sets the PR to allow auto-merging for patch and minor
      # updates if all checks pass
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
