# Trigger Circle CI to build PRs that don't come from project editor.
# After the "buildme" label is applied to external PRs this job will trigger them in Circle CI.

name: "external_pr"

on:
  pull_request:
    types: [ labeled, synchronize ]

jobs:
  trigger_circleci:
    # When applying the label originally and for additional commits.
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'buildme')
      || (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'buildme'))
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pipeline
        env:
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
        run: |
          PULL_REQUEST_NUMBER=$(echo "$GITHUB_REF" | cut -d/ -f3) \
          && echo "Triggering pipeline for PR #${PULL_REQUEST_NUMBER}" \
          && curl --request POST \
                  --url https://circleci.com/api/v2/project/github/coda/packs-sdk/pipeline \
                  --header "Circle-Token: ${CIRCLE_TOKEN}" \
                  --header 'Content-Type: application/json' \
                  --data "{\"branch\": \"pull/${PULL_REQUEST_NUMBER}/head\"}" \
                  --silent --show-error --fail
