on:
  pull_request:
    types: [ labeled, synchronize ]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'buildme')
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Build in Circle CI"
